"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "FR" | "EN";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  FR: {
    accueil: "Accueil",
    apropos: "À propos",
    services: "Services",
    realisations: "Réalisations",
    actualites: "Actualités",
    contact: "Contact",
    connexion: "Connexion",
    prendre_rdv: "Prendre RDV",
    votre_partenaire: "VOTRE PARTENAIRE",
    en_excellence: "EN EXCELLENCE",
    decouvrir_excellence: "Découvrir l'Excellence",
    audit_conformite: "AUDIT & CONFORMITÉ",
    audit_desc: "Anticipez les risques et assurez la conformité de votre organisation avec nos experts certifiés ISO.",
    formation_certifiante: "FORMATION CERTIFIANTE",
    formation_desc: "Développez les compétences de vos équipes avec nos programmes aux standards internationaux.",
    conseil_strategique: "CONSEIL STRATÉGIQUE",
    conseil_desc: "Optimisez votre gouvernance et vos processus pour une performance durable et mesurable.",
    votre_competitivite: "Votre compétitivité,",
    notre_priorite: "notre priorité.",
    nos_services: "Nos Services",
    nos_realisations: "Nos Réalisations",
    a_propos_beg: "À propos de BEG",
    valeur_ajoutee: "VALEUR AJOUTÉE",
    pourquoi: "Pourquoi",
    choisir_nous: "Nous choisir.",
    approche_impact: "Une approche orientée impact pour garantir votre succès.",
    combinaison_expertise: "Nous combinons expertise de haut niveau et méthodologies agiles pour transformer vos processus en leviers de croissance.",
    decouvrir_vision: "Découvrir notre vision",
    engagement_resultats: "Engagement Résultats",
    expert_certifies: "Experts expérimentés et certifiés",
    methodologie_pratique: "Méthodologie pratique et orientée résultats",
    accompagnement_perso: "Accompagnement personnalisé",
    suivi_jusqua_resultat: "Suivi jusqu'à obtention des résultats",
    formations_phares_label: "FORMATIONS PHARES",
    phares: "Phares.",
    programmes_certifiants: "Programmes certifiants et accompagnements stratégiques pour aligner votre organisation sur les standards mondiaux.",
    voir_catalogue: "Voir tout le catalogue",
    management_qualite: "Management de la qualité",
    securite_information: "Sécurité de l'information",
    gestion_projet: "Gestion de projet",
    performance_agilite: "Performance & Agilité",
    leadership_management: "Leadership & Management",
    excellence_dirigeante: "Excellence Dirigeante",
    marketing_digital: "Marketing Digital",
    croissance_visibilite: "Croissance & Visibilité",
    entreprises_accompagnees: "ENTREPRISES ACCOMPAGNÉES",
    experts_certifies_inter: "CERTIFIÉS INTERNATIONAUX",
    presence_continentale: "PRÉSENCE CONTINENTALE",
    approche_resultats_label: "APPROCHE RÉSULTATS",
    excellence_operationnelle: "Excellence",
    operationnelle: "Opérationnelle.",
    aide_organisations: "Nous aidons les organisations à atteindre des standards internationaux et améliorer durablement leurs performances.",
    experts_value: "Experts",
    afrique_value: "Afrique",
    cibles_strategiques: "CIBLES STRATÉGIQUES",
    a_qui_adressent: "À qui s’adressent",
    nos_services_label: "Nos services.",
    entreprises_title: "Entreprises",
    precision_accompagnement: "de précision dans l'accompagnement normatif.",
    institutions_publiques: "Institutions Publiques",
    fluidification_processus: "de fluidification des processus.",
    responsables: "Responsables",
    processus_automatises: "processus automatisés et maîtrisés.",
    semaines: "semaines",
    moyenne_deploiement: "de moyenne de déploiement.",
    entrepreneurs: "Entrepreneurs",
    visionnaires_changement: "Visionnaires du changement.",
    sante: "Santé",
    education: "Éducation",
    justice: "Justice",
    finance: "Finance",
    impasse_normative: "L'impasse normative",
    impasse_desc: "La complexité des standards internationaux freine souvent l'ambition des entreprises locales et leur accès aux marchés mondiaux.",
    instabilite_op: "L'instabilité opérationnelle",
    instabilite_desc: "Des processus non structurés entraînent une perte de qualité constante et une stagnation de la performance globale.",
    plafond_verre: "Le plafond de verre",
    plafond_desc: "L'absence d'une certification ISO reconnue limite la crédibilité et bloque l'accès aux appels d'offres stratégiques.",
    nos_expertises_label: "NOS SERVICES",
    nos_title: "Nos",
    expertises_title: "expertises.",
    accompagnement_strategique: "Accompagnement stratégique et opérationnel pour transformer vos défis en leviers de performance durable.",
    accompagnement_certification: "Accompagnement à la certification",
    accompagnement_desc_short: "De l’audit initial à l’obtention de votre certification ISO. Nous vous guidons à chaque étape du processus.",
    formation_pro_certifiante: "Formation professionnelle & certifiante",
    formation_pro_desc: "Programmes alignés aux standards internationaux (ISO, management, digital…). Développez les talents de demain.",
    audit_conformite_iso: "Audit & conformité ISO",
    audit_conformite_desc: "Identifiez vos écarts et assurez votre conformité aux normes mondiales avec nos experts dédiés.",
    conseil_structuration: "Conseil & structuration organisationnelle",
    conseil_structuration_desc: "Optimisez votre organisation et vos processus pour plus de performance. Une approche sur mesure pour votre structure.",
    pret_accelerer: "Prêt à accélérer ?",
    partenaire_croissance: "Votre Partenaire en",
    croissance_normative_title: "Croissance Normative.",
    prendre_rdv_cta: "Prendre un RDV",
    telephone_label: "Téléphone",
    resultats_impact: "RÉSULTATS / IMPACT",
    resultats_title: "Résultats",
    concrets_title: "concrets.",
    perf_internes: "Performances Internes",
    perf_internes_desc: "Amélioration significative de la productivité et de l'efficacité opérationnelle de vos équipes.",
    certifications_iso_title: "Certifications ISO",
    certifications_iso_desc: "Accompagnement réussi jusqu'à l'obtention et le renouvellement de vos certificats internationaux.",
    optimisation_processus_title: "Optimisation Processus",
    optimisation_processus_desc: "Structuration et fluidification des processus métier pour une meilleure agilité organisationnelle.",
    competences_title: "Compétences",
    competences_desc: "Renforcement durable des capacités managériales et techniques des collaborateurs.",
    reseau_confiance: "Notre réseau de confiance",
    qui_sommes_nous: "QUI SOMMES NOUS ?",
    beg_desc_long: "BEG est un cabinet panafricain d'audit, de conseil et de formation. Nous propulsons l'excellence opérationnelle par les standards ISO, avec une philosophie alliant rigueur mondiale et agilité locale.",
    discutons_projet: "Discutons de votre projet",
    a_propos_monumental: "À PROPOS",
    decouvrez_equipe: "Découvrez l'équipe derrière l'excellence",
    consultants: "Consultants",
    voir_bureaux: "Voir nos bureaux",
    vision_experts: "Une vision partagée par des experts qui repoussent les limites chaque jour.",
    experts_collaborent: "Plus de 50 experts collaborent quotidiennement pour offrir des solutions d'audit et de conseil à travers le continent.",
    nous_rejoindre: "Nous rejoindre",
    fondateur: "Fondateur",
    pense_realite: "Pensé pour la réalité de vos flux de travail",
    trouvez_point_depart: "Trouvez le point de départ idéal",
    identifiez_leviers: "Identifiez les leviers de croissance avec nos diagnostics certifiés et nos filtres stratégiques.",
    filtres_strategiques_label: "Filtres Stratégiques",
    triez_priorite: "Triez par priorité ou par impact immédiat.",
    synchronisation_iso_label: "Synchronisation ISO",
    maj_automatique: "Mise à jour automatique des normes de conformité.",
    notre_mission: "Mission",
    mission_desc: "Apporter une expertise stratégique aux organisations africaines pour combler les écarts de performance et créer une valeur durable par l'excellence opérationnelle.",
    notre_vision_title: "Vision",
    vision_desc_about: "Devenir le partenaire de référence en Afrique, en propulsant le continent vers les plus hauts standards mondiaux de qualité et de gouvernance.",
    nos_valeurs_title: "Valeurs",
    valeur_pro: "Professionnalisme",
    valeur_rigueur: "Rigueur",
    valeur_excellence: "Excellence",
    valeur_innovation: "Innovation",
    valeur_confiance: "Confiance",
    valeur_accompagnement: "Accompagnement",
    valeur_engagement: "Engagement",
    expertise_iso_title: "Expertise ISO",
    expertise_iso_cat: "Certification",
    conseil_strat_title: "Conseil Stratégique",
    conseil_strat_cat: "Audit",
    innovation_formation_title: "Innovation & Formation",
    innovation_formation_cat: "Académie",
    educbest_desc: "Développement d'une plateforme éducative complète pour l'apprentissage en ligne, offrant des ressources pédagogiques interactives et un suivi personnalisé.",
    bestqhse_desc: "Conception et déploiement d'un portail dédié à la Qualité, Hygiène, Sécurité et Environnement (QHSE), centralisant les normes et les audits.",
    bestmarket_desc: "Création d'une marketplace e-commerce B2C innovante pour le marché béninois, intégrant des solutions de paiement localisées et une gestion logistique avancée.",
    cat_audit: "Audit",
    cat_certification: "Certification",
    cat_conseil: "Conseil",
    cat_digital: "Digital",
    nos_realisations_monumental: "RÉALISATIONS",
    voir_le_projet: "Voir le projet",
    actualites_monumental: "ACTUALITÉS",
    derniers_articles: "Nos derniers articles",
    lire_plus: "Lire plus",
    rechercher_article: "Rechercher un article...",
    populaires: "Populaires",
    categorie_label: "Catégorie",
    auteur_label: "Auteur",
    temps_lecture_label: "Temps de lecture",
    min_read: "min de lecture",
    partager_article: "Partager l'article",
    articles_similaires: "Articles similaires",
    en_attente: "En attente",
    publie: "Publié",
    repondre: "Répondre",
    votre_nom: "Votre nom *",
    votre_commentaire: "Votre commentaire *",
    votre_reponse: "Votre réponse...",
    commentaire_soumis: "Commentaire soumis !",
    invisible_validation: "Il sera visible après validation par notre équipe.",
    validation_notice: "Les commentaires sont soumis à validation avant publication.",
    envoyer: "Envoyer",
    annuler: "Annuler",
    article_introuvable: "Article introuvable",
    retour_aux_actualites: "Retour aux actualités",
    laisser_un_commentaire: "Laisser un commentaire",
    copier: "Copier",
    copie: "Copié !",
    jaime: "J'aime",
    curieux_projets: "Nous sommes curieux de découvrir vos projets.",
    type_de_service: "Type de service",
    budget: "Budget",
    nom_complet: "Nom complet",
    votre_email_pro: "E-mail professionnel",
    envoyer_message: "ENVOYER LE MESSAGE",
    excellence_citation: "L'EXCELLENCE EST UN RÉSULTAT DE L'AGILITÉ ET DU RESPECT DES STANDARDS.",
    cabinet_panafricaen: "CABINET PANAFRICAIN D'AUDIT, DE CONSEIL ET DE FORMATION.",
    suivez_nous: "Suivez-nous",
    audit_diag: "Audit & Diagnostic",
    audit_diag_desc: "Évaluation rigoureuse de vos systèmes pour garantir la conformité et identifier les leviers d'amélioration.",
    acc_certification: "Accompagnement Certification",
    acc_certification_desc: "Un parcours structuré de l'audit initial jusqu'à l'obtention de votre certification internationale.",
    conseil_strat: "Conseil & Stratégie",
    conseil_strat_desc: "Optimisation de vos processus et déploiement de stratégies pour une croissance durable.",
    solutions_digitales_title: "Solutions Digitales",
    solutions_digitales_desc: "Transformation numérique et outils intelligents pour piloter votre performance en temps réel.",
    objectifs: "Objectifs",
    clientele: "Clientèle",
    processus_travail: "Processus de travail",
    benefices: "Bénéfices",
    resultats: "Résultats",
    demander_devis: "Demander un devis",
    restez_informe: "Restez informé des dernières normes et opportunités !",
    sinscrire: "S'inscrire",
    votre_adresse_email: "Votre adresse email",
    accept_terms: "En vous inscrivant, vous acceptez nos termes et conditions.",
    expertise_iso: "Expertise ISO",
    audit_pme: "Audit PME",
    formation_2024: "Formation 2024",

    langue_label: "Langue",
    francais: "Français",
    anglais: "Anglais",
    voix_entrepreneurs: "La Voix des Entrepreneurs",
    ils_reinventent: "Ils réinventent",
    economie: "l'économie.",
    centaines_entrepreneurs: "Des centaines d'entrepreneurs ont transformé leur trajectoire grâce au BEG.",
    voir_histoire: "Voir l'histoire",
  },
  EN: {
    accueil: "Home",
    apropos: "About",
    services: "Services",
    realisations: "Projects",
    actualites: "News",
    contact: "Contact",
    connexion: "Login",
    prendre_rdv: "Book an Appt",
    votre_partenaire: "YOUR PARTNER",
    en_excellence: "IN EXCELLENCE",
    decouvrir_excellence: "Discover Excellence",
    audit_conformite: "AUDIT & COMPLIANCE",
    audit_desc: "Anticipate risks and ensure your organization's compliance with our ISO-certified experts.",
    formation_certifiante: "CERTIFIED TRAINING",
    formation_desc: "Develop your teams' skills with our international standard programs.",
    conseil_strategique: "STRATEGIC CONSULTING",
    conseil_desc: "Optimize your governance and processes for sustainable and measurable performance.",
    votre_competitivite: "Your competitiveness,",
    notre_priorite: "our priority.",
    nos_services: "Our Services",
    nos_realisations: "Our Projects",
    a_propos_beg: "About BEG",
    valeur_ajoutee: "ADDED VALUE",
    pourquoi: "Why",
    choisir_nous: "Choose us.",
    approche_impact: "An impact-oriented approach to guarantee your success.",
    combinaison_expertise: "We combine high-level expertise and agile methodologies to transform your processes into growth levers.",
    decouvrir_vision: "Discover our vision",
    engagement_resultats: "Results Commitment",
    expert_certifies: "Experienced and certified experts",
    methodologie_pratique: "Practical and results-oriented methodology",
    accompagnement_perso: "Personalized support",
    suivi_jusqua_resultat: "Follow-up until results are obtained",
    formations_phares_label: "KEY TRAININGS",
    phares: "Highlights.",
    programmes_certifiants: "Certifying programs and strategic support to align your organization with global standards.",
    voir_catalogue: "View full catalog",
    management_qualite: "Quality management",
    securite_information: "Information security",
    gestion_projet: "Project management",
    performance_agilite: "Performance & Agility",
    leadership_management: "Leadership & Management",
    excellence_dirigeante: "Executive Excellence",
    marketing_digital: "Digital Marketing",
    croissance_visibilite: "Growth & Visibility",
    entreprises_accompagnees: "SUPPORTED COMPANIES",
    experts_certifies_inter: "INTERNATIONAL CERTIFIED",
    presence_continentale: "CONTINENTAL PRESENCE",
    approche_resultats_label: "RESULTS APPROACH",
    excellence_operationnelle: "Operational",
    operationnelle: "Excellence.",
    aide_organisations: "We help organizations achieve international standards and sustainably improve their performance.",
    experts_value: "Experts",
    afrique_value: "Africa",
    cibles_strategiques: "STRATEGIC TARGETS",
    a_qui_adressent: "Who are we",
    nos_services_label: "Addressing.",
    entreprises_title: "Companies",
    precision_accompagnement: "precision in normative support.",
    institutions_publiques: "Public Institutions",
    fluidification_processus: "process fluidification.",
    responsables: "Managers",
    processus_automatises: "automated and mastered processes.",
    semaines: "weeks",
    moyenne_deploiement: "average deployment time.",
    entrepreneurs: "Entrepreneurs",
    visionnaires_changement: "Visionaries of change.",
    sante: "Health",
    education: "Education",
    justice: "Justice",
    finance: "Finance",
    impasse_normative: "Normative deadlock",
    impasse_desc: "The complexity of international standards often hinders the ambition of local companies and their access to global markets.",
    instabilite_op: "Operational instability",
    instabilite_desc: "Unstructured processes lead to a constant loss of quality and a stagnation of overall performance.",
    plafond_verre: "The glass ceiling",
    plafond_desc: "The absence of a recognized ISO certification limits credibility and blocks access to strategic tenders.",
    nos_expertises_label: "OUR SERVICES",
    nos_title: "Our",
    expertises_title: "expertises.",
    accompagnement_strategique: "Strategic and operational support to transform your challenges into sustainable performance levers.",
    accompagnement_certification: "Certification support",
    accompagnement_desc_short: "From initial audit to obtaining your ISO certification. We guide you through every step of the process.",
    formation_pro_certifiante: "Professional & certifying training",
    formation_pro_desc: "Programs aligned with international standards (ISO, management, digital…). Develop the talents of tomorrow.",
    audit_conformite_iso: "Audit & ISO compliance",
    audit_conformite_desc: "Identify your gaps and ensure your compliance with global standards with our dedicated experts.",
    conseil_structuration: "Consulting & organizational structuring",
    conseil_structuration_desc: "Optimize your organization and processes for more performance. A tailor-made approach for your structure.",
    pret_accelerer: "Ready to accelerate?",
    partenaire_croissance: "Your Partner in",
    croissance_normative_title: "Normative Growth.",
    prendre_rdv_cta: "Book an Appointment",
    telephone_label: "Phone",
    resultats_impact: "RESULTS / IMPACT",
    resultats_title: "Concrete",
    concrets_title: "results.",
    perf_internes: "Internal Performance",
    perf_internes_desc: "Significant improvement in the productivity and operational efficiency of your teams.",
    certifications_iso_title: "ISO Certifications",
    certifications_iso_desc: "Successful support until obtaining and renewing your international certificates.",
    optimisation_processus_title: "Process Optimization",
    optimisation_processus_desc: "Structuring and fluidification of business processes for better organizational agility.",
    competences_title: "Skills",
    competences_desc: "Sustainable capacity building of managerial and technical skills of employees.",
    reseau_confiance: "Our network of trust",
    qui_sommes_nous: "WHO ARE WE?",
    beg_desc_long: "BEG is a pan-African audit, consulting and training firm. We drive operational excellence through ISO standards, with a philosophy combining global rigor and local agility.",
    discutons_projet: "Let's discuss your project",
    a_propos_monumental: "ABOUT",
    decouvrez_equipe: "Discover the team behind excellence",
    consultants: "Consultants",
    voir_bureaux: "See our offices",
    vision_experts: "A vision shared by experts who push the limits every day.",
    experts_collaborent: "More than 50 experts collaborate daily to offer audit and consulting solutions across the continent.",
    nous_rejoindre: "Join us",
    fondateur: "Founder",
    pense_realite: "Thought for the reality of your workflows",
    trouvez_point_depart: "Find the ideal starting point",
    identifiez_leviers: "Identify growth levers with our certified diagnostics and strategic filters.",
    filtres_strategiques_label: "Strategic Filters",
    triez_priorite: "Sort by priority or immediate impact.",
    synchronisation_iso_label: "ISO Synchronization",
    maj_automatique: "Automatic update of compliance standards.",
    notre_mission: "Mission",
    mission_desc: "Bring strategic expertise to African organizations to bridge performance gaps and create sustainable value through operational excellence.",
    notre_vision_title: "Vision",
    vision_desc_about: "Become the reference partner in Africa, propelling the continent towards the highest global standards of quality and governance.",
    nos_valeurs_title: "Values",
    valeur_pro: "Professionalism",
    valeur_rigueur: "Rigor",
    valeur_excellence: "Excellence",
    valeur_innovation: "Innovation",
    valeur_confiance: "Trust",
    valeur_accompagnement: "Support",
    valeur_engagement: "Engagement",
    expertise_iso_title: "ISO Expertise",
    expertise_iso_cat: "Certification",
    conseil_strat_title: "Strategic Consulting",
    conseil_strat_cat: "Audit",
    innovation_formation_title: "Innovation & Training",
    innovation_formation_cat: "Academy",
    educbest_desc: "Development of a complete educational platform for online learning, offering interactive educational resources and personalized follow-up.",
    bestqhse_desc: "Design and deployment of a portal dedicated to Quality, Health, Safety and Environment (QHSE), centralizing standards and audits.",
    bestmarket_desc: "Creation of an innovative B2C e-commerce marketplace for the Beninese market, integrating localized payment solutions and advanced logistics management.",
    cat_audit: "Audit",
    cat_certification: "Certification",
    cat_conseil: "Consulting",
    cat_digital: "Digital",
    nos_realisations_monumental: "PROJECTS",
    voir_le_projet: "View project",
    actualites_monumental: "NEWS",
    derniers_articles: "Our latest articles",
    lire_plus: "Read more",
    rechercher_article: "Search an article...",
    populaires: "Popular",
    categorie_label: "Category",
    auteur_label: "Author",
    temps_lecture_label: "Read time",
    min_read: "min read",
    partager_article: "Share article",
    articles_similaires: "Similar articles",
    en_attente: "Pending",
    publie: "Published",
    repondre: "Reply",
    votre_nom: "Your name *",
    votre_commentaire: "Your comment *",
    votre_reponse: "Your reply...",
    commentaire_soumis: "Comment submitted!",
    invisible_validation: "It will be visible after validation by our team.",
    validation_notice: "Comments are subject to validation before publication.",
    envoyer: "Send",
    annuler: "Cancel",
    article_introuvable: "Article not found",
    retour_aux_actualites: "Back to news",
    laisser_un_commentaire: "Leave a comment",
    copier: "Copy",
    copie: "Copied!",
    jaime: "Likes",
    curieux_projets: "We are curious to discover your projects.",
    type_de_service: "Type of service",
    budget: "Budget",
    nom_complet: "Full name",
    votre_email_pro: "Professional email",
    envoyer_message: "SEND THE MESSAGE",
    excellence_citation: "EXCELLENCE IS A RESULT OF AGILITY AND COMPLIANCE WITH STANDARDS.",
    cabinet_panafricaen: "PAN-AFRICAN AUDIT, CONSULTING AND TRAINING FIRM.",
    suivez_nous: "Follow us",
    audit_diag: "Audit & Diagnostic",
    audit_diag_desc: "Rigorous evaluation of your systems to ensure compliance and identify levers for improvement.",
    acc_certification: "Certification Support",
    acc_certification_desc: "A structured path from the initial audit to obtaining your international certification.",
    conseil_strat: "Consulting & Strategy",
    conseil_strat_desc: "Optimization of your processes and deployment of strategies for sustainable growth.",
    solutions_digitales_title: "Digital Solutions",
    solutions_digitales_desc: "Digital transformation and intelligent tools to monitor your performance in real time.",
    objectifs: "Objectives",
    clientele: "Clientele",
    processus_travail: "Work Process",
    benefices: "Benefits",
    resultats: "Results",
    demander_devis: "Request a quote",
    restez_informe: "Stay informed of the latest standards and opportunities!",
    sinscrire: "Subscribe",
    votre_adresse_email: "Your email address",
    accept_terms: "By subscribing, you accept our terms and conditions.",
    expertise_iso: "ISO Expertise",
    audit_pme: "SME Audit",
    formation_2024: "2024 Training",

    langue_label: "Language",
    francais: "French",
    anglais: "English",
    voix_entrepreneurs: "The Voice of Entrepreneurs",
    ils_reinventent: "They reinvent",
    economie: "the economy.",
    centaines_entrepreneurs: "Hundreds of entrepreneurs have transformed their trajectory thanks to BEG.",
    voir_histoire: "See history",
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("FR");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && (savedLang === "FR" || savedLang === "EN")) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const toggleLanguage = () => {
    const newLang = language === "FR" ? "EN" : "FR";
    setLanguage(newLang);
  };

  const t = (key: string) => {
    const section = translations[language];
    return (section as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
